ifdef CONFIG_MACH_JIR
obj-$(CONFIG_SH_CAMERA) += sh_maincamdrv_jir.o
else
ifdef CONFIG_MACH_BEC
obj-$(CONFIG_SH_CAMERA) += sh_maincamdrv_bec.o
obj-$(CONFIG_SH_CAMERA) += sh_maincam_power_ctrl.o
endif
endif
